spring:
  application:
    name: gatewayserver
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    gateway:
      server:
        webflux:
          discovery: # connect to Eureka
            locator: # lookup services from Eureka
              enabled: true  # Enable service discovery routing
              lower-case-service-id: true  # Optional: allow lowercase service IDs
          httpclient:
            connect-timeout: 1000
            response-timeout: 5s
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 2s
      timeout: 1s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: gatewayserver
    description: EazyBank Gateway Server Application
    version: 1.0.0

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 2