spring:
  application:
    name: gatewayserver
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    gateway:
      server:
        webflux:
          discovery: # connect to Eureka
            locator: # lookup services from Eureka
              enabled: true  # Enable service discovery routing
              lower-case-service-id: true  # Optional: allow lowercase service IDs
          httpclient:
            connect-timeout: 1000
            response-timeout: 5s
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 5s
      timeout: 5s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true
  micrometer:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: gatewayserver
    description: EazyBank Gateway Server Application
    version: 1.0.0

logging:
  level:
    com:
      eazybytes:
        gatewayserver: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 2